spring:
  application:
    name: smartexpensetracker

  profiles:
    active: prod

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET:smartexpensetracker-secret-key-2024-spring-boot-jwt-authentication}
  expiration: 86400000

logging:
  level:
    root: INFO
    com.prl.smartexpensetracker: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG